[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "django>=5.1.7",
    "pandas>=2.2.3",
    "requests>=2.32.3",
    "xlsxwriter>=3.2.2",
]
